// AUTO-GENERATED by scripts/build-tokens.mjs from tokens/tokens.json
// Do not edit. Run `npm run tokens` after tokens.json changes.

export const themes = {
  "light": {
    "--color-background": "#FFFFFF",
    "--color-border": "#E0E0E8",
    "--color-border-subtle": "#F0F0F5",
    "--color-card-bg": "#FFFFFF",
    "--color-primary": "#3D6BF5",
    "--color-success": "#33B866",
    "--color-surface": "#F7F7FA",
    "--color-surface-elevated": "#FFFFFF",
    "--color-switch-on": "#3D6BF5",
    "--color-tab-active": "#3D6BF5",
    "--color-tab-inactive": "#9999A8",
    "--color-text-primary": "#1A1A21",
    "--color-text-secondary": "#6B6B7A",
    "--color-text-tertiary": "#9999A8",
    "--color-warning": "#F5AD2E"
  },
  "dark": {
    "--color-background": "#0F0F17",
    "--color-border": "#292933",
    "--color-border-subtle": "#1A1A21",
    "--color-card-bg": "#292933",
    "--color-primary": "#5C87FA",
    "--color-success": "#33B866",
    "--color-surface": "#1A1A21",
    "--color-surface-elevated": "#292933",
    "--color-switch-on": "#5C87FA",
    "--color-tab-active": "#5C87FA",
    "--color-tab-inactive": "#52525E",
    "--color-text-primary": "#FFFFFF",
    "--color-text-secondary": "#9999A8",
    "--color-text-tertiary": "#52525E",
    "--color-warning": "#F5AD2E"
  },
  "ocean": {
    "--color-background": "#081F3D",
    "--color-border": "#14426B",
    "--color-border-subtle": "#0D2E52",
    "--color-card-bg": "#14426B",
    "--color-primary": "#2EC4B8",
    "--color-success": "#1FA699",
    "--color-surface": "#0D2E52",
    "--color-surface-elevated": "#14426B",
    "--color-switch-on": "#2EC4B8",
    "--color-tab-active": "#2EC4B8",
    "--color-tab-inactive": "#1F5C85",
    "--color-text-primary": "#FFFFFF",
    "--color-text-secondary": "#A6D1EB",
    "--color-text-tertiary": "#1F5C85",
    "--color-warning": "#F5AD2E"
  }
} as const;

export const primitives = {
  "radius": {
    "1": 1,
    "2": 2,
    "3": 3,
    "8": 8,
    "12": 12,
    "14": 14,
    "16": 16,
    "40": 40,
    "pill": 999
  },
  "text": {
    "10": 10,
    "12": 12,
    "13": 13,
    "14": 14,
    "15": 15,
    "16": 16,
    "18": 18,
    "20": 20,
    "22": 22,
    "28": 28
  },
  "space": {
    "1": 1,
    "3": 3,
    "4": 4,
    "5": 5,
    "6": 6,
    "8": 8,
    "9": 9,
    "10": 10,
    "11": 11,
    "12": 12,
    "14": 14,
    "16": 16,
    "20": 20,
    "22": 22,
    "24": 24,
    "28": 28,
    "32": 32,
    "36": 36,
    "40": 40,
    "48": 48,
    "52": 52,
    "56": 56
  }
} as const;

export type ThemeName = keyof typeof themes;
export const themeNames = Object.keys(themes) as ThemeName[];
