// AUTO-GENERATED by scripts/build-tokens.mjs from tokens/tokens.json
// Do not edit. Run `npm run tokens` after tokens.json changes.

export const themes = {
  "light": {
    "--color-bg": "#FFFFFF",
    "--color-surface": "#F6F7F9",
    "--color-text": "#0E1116",
    "--color-muted": "#5B6472",
    "--color-border": "#E3E6EB",
    "--color-primary": "#2F5BFF",
    "--color-primary-fg": "#FFFFFF",
    "--color-accent": "#0FB5A6",
    "--color-danger": "#D63A2F"
  },
  "dark": {
    "--color-bg": "#0B0D11",
    "--color-surface": "#14181F",
    "--color-text": "#EDF0F4",
    "--color-muted": "#98A2B3",
    "--color-border": "#232935",
    "--color-primary": "#6D8BFF",
    "--color-primary-fg": "#0B0D11",
    "--color-accent": "#2BD6C4",
    "--color-danger": "#FF6B5E"
  },
  "sunset": {
    "--color-bg": "#1A1116",
    "--color-surface": "#241820",
    "--color-text": "#FDF3EC",
    "--color-muted": "#C4A79B",
    "--color-border": "#3A2730",
    "--color-primary": "#FF7A45",
    "--color-primary-fg": "#1A1116",
    "--color-accent": "#FFC46B",
    "--color-danger": "#FF4D6D"
  }
} as const;

export const primitives = {
  "radius": {
    "sm": 6,
    "md": 12,
    "lg": 20,
    "pill": 999
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 24,
    "6": 32,
    "7": 48
  },
  "text": {
    "xs": 12,
    "sm": 14,
    "base": 16,
    "lg": 20,
    "xl": 28,
    "display": 40
  }
} as const;

export type ThemeName = keyof typeof themes;
export const themeNames = Object.keys(themes) as ThemeName[];
