#!/usr/bin/env node
// tokens/tokens.json  ->  src/theme/tokens.gen.ts
// ponytail: one file in, one file out. No token pipeline framework.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const src = JSON.parse(readFileSync(new URL("../tokens/tokens.json", import.meta.url), "utf8"));

const cssVar = (name) => `--${name.replace(/\//g, "-")}`;
const camel = (name) => name.replace(/[-/](\w)/g, (_, c) => c.toUpperCase());

const theme = src.collections.theme;
const themes = Object.fromEntries(
  theme.modes.map((mode) => [
    mode,
    Object.fromEntries(
      Object.entries(theme.variables).map(([name, byMode]) => {
        const v = byMode[mode];
        if (v === undefined) throw new Error(`token "${name}" has no value for mode "${mode}"`);
        return [cssVar(name), v];
      })
    ),
  ])
);

const prim = src.collections.primitives.variables;
const primitives = {};
for (const [name, byMode] of Object.entries(prim)) {
  const [group, key] = name.split("/");
  (primitives[group] ??= {})[camel(key)] = byMode.value;
}

// The scale is read off the Figma design, so a value can disappear when the
// designer stops using it. NativeWind drops an unknown class in silence, which
// would show up as a broken screen rather than an error. Fail here instead.
const sources = [];
const collect = (dir) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const path = `${dir}/${e.name}`;
    if (e.isDirectory()) collect(path);
    else if (/\.(tsx?|jsx?)$/.test(e.name)) sources.push(readFileSync(path, "utf8"));
  }
};
collect(new URL("../src", import.meta.url).pathname);
sources.push(readFileSync(new URL("../App.tsx", import.meta.url), "utf8"));

const GROUP = {
  rounded: "radius",
  text: "text",
  p: "space", px: "space", py: "space", pt: "space", pb: "space", pl: "space", pr: "space",
  m: "space", mx: "space", my: "space", mt: "space", mb: "space", ml: "space", mr: "space",
  gap: "space", w: "space", h: "space",
};
const missing = new Set();
for (const src of sources) {
  for (const [, prefix, key] of src.matchAll(/\b([a-z]{1,7})-(\d+|pill)\b/g)) {
    const group = GROUP[prefix];
    if (group && !prim[`${group}/${key}`]) missing.add(`${prefix}-${key} (needs ${group}/${key})`);
  }
}
if (missing.size) {
  throw new Error(
    `The design no longer defines every value the app uses:\n  ${[...missing].sort().join("\n  ")}\n` +
      "Either the designer dropped it, or the component should use a value that is still in the scale."
  );
}

const out = `// AUTO-GENERATED by scripts/build-tokens.mjs from tokens/tokens.json
// Do not edit. Run \`npm run tokens\` after tokens.json changes.

export const themes = ${JSON.stringify(themes, null, 2)} as const;

export const primitives = ${JSON.stringify(primitives, null, 2)} as const;

export type ThemeName = keyof typeof themes;
export const themeNames = Object.keys(themes) as ThemeName[];
`;

writeFileSync(new URL("../src/theme/tokens.gen.ts", import.meta.url), out);
console.log(`tokens: ${theme.modes.length} themes, ${Object.keys(theme.variables).length} color vars, ${Object.keys(prim).length} primitives -> src/theme/tokens.gen.ts`);
