#!/usr/bin/env node
// tokens/tokens.json  ->  src/theme/tokens.gen.ts
// ponytail: one file in, one file out. No token pipeline framework.
import { readFileSync, writeFileSync } from "node:fs";

const src = JSON.parse(readFileSync(new URL("../tokens/tokens.json", import.meta.url), "utf8"));

const cssVar = (name) => `--${name.replace(/\//g, "-")}`;
const camel = (name) => name.replace(/[-/](\w)/g, (_, c) => c.toUpperCase());

const theme = src.collections.theme;
const themes = Object.fromEntries(
  theme.modes.map((mode) => [
    mode,
    Object.fromEntries(
      Object.entries(theme.variables).map(([name, byMode]) => {
        const v = byMode[mode];
        if (v === undefined) throw new Error(`token "${name}" has no value for mode "${mode}"`);
        return [cssVar(name), v];
      })
    ),
  ])
);

const prim = src.collections.primitives.variables;
const primitives = {};
for (const [name, byMode] of Object.entries(prim)) {
  const [group, key] = name.split("/");
  (primitives[group] ??= {})[camel(key)] = byMode.value;
}

const out = `// AUTO-GENERATED by scripts/build-tokens.mjs from tokens/tokens.json
// Do not edit. Run \`npm run tokens\` after tokens.json changes.

export const themes = ${JSON.stringify(themes, null, 2)} as const;

export const primitives = ${JSON.stringify(primitives, null, 2)} as const;

export type ThemeName = keyof typeof themes;
export const themeNames = Object.keys(themes) as ThemeName[];
`;

writeFileSync(new URL("../src/theme/tokens.gen.ts", import.meta.url), out);
console.log(`tokens: ${theme.modes.length} themes, ${Object.keys(theme.variables).length} color vars, ${Object.keys(prim).length} primitives -> src/theme/tokens.gen.ts`);
